package com.lx.oneteamproject.fragment

enum class FragmentType {

    LOGIN,
    SIGNUP,
    MAIN,
    REPORT,
    REPORTFREE,
    REPORTFORM,
    REPORTCHECK,
    NEARSITUATIONMAP,
    NEARSTATISTICSMAP,
    REPORTDETAILS,
    MYREPORTLIST,
    NATIONALACTIONARTICLE,
    NATIONALACTIONVIEDO,
    NEARSOCIALDISATER,
    NEARRISKINFORMATION,
    NEARNATURALDISATER,
    NEARSAFETYFACILITY,
    NEARSTATISTICSMAP_SOCIAL,
    NEARSTATISTICSMAP_RISK,
    NEARSTATISTICSMAP_NATURAL,
    NEARSTATISTICSMAP_SAFETY,
    REPORTEX


}